name: End-To-End Tests
on: [push]

jobs:
cypress-chrome:
runs-on: ubuntu-22.04
steps:
  - name: Chechkout repo
      uses: actions/checkout@v4

  - name: Install dependencies
      run: npm install

   - name: Run Cypress on Chrome
      run: npm run cy:chrome   

cypress-report:
    needs: [cypress-chrome]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress and generate Mochawesome report
        run: npx cypress run

      - name: Upload Mochawesome report
        uses: actions/upload-artifact@v4
        if: always()
        with: 
          name: cy-report
          path: cypress/reports/html  
